import {newSession,restoreSession,recordAttempt,totalScore,completedCount,lessonDone,demoProgress,shuffle,pageScore,STORAGE_KEY} from './state.js';
import {questions as iodineQuestions,isComplete,isCorrect} from './questions.js';
import {lessons,courses,learningIds} from './course-data.js';
import {renderExplorations,refreshExplorations} from './explorations.js';
import {renderActivity,stopActivity} from './activities.js';
let questions=iodineQuestions;

const $=selector=>document.querySelector(selector);
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const keywordKinds={醣類:'carb',澱粉:'carb',葡萄糖:'carb',纖維素:'carb',肝糖:'carb',蛋白質:'protein',脂質:'fat',水:'water',礦物質:'mineral',維生素:'vitamin',碘液:'method',本氏液:'method',觀察:'observation',證據:'evidence',結論:'evidence',限制:'limit'};
const keywordPattern=new RegExp(`(${Object.keys(keywordKinds).sort((a,b)=>b.length-a.length).join('|')})`,'g');
function colorizeKeywords(){document.querySelectorAll('.paper p,.paper li,.concept-node,.page-heading>p,.hero-lead').forEach(root=>{const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT),nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);for(const node of nodes){if(node.parentElement.closest('mark,button,label,input,select,option,.feedback')||!keywordPattern.test(node.data)){keywordPattern.lastIndex=0;continue;}keywordPattern.lastIndex=0;const frag=document.createDocumentFragment();for(const part of node.data.split(keywordPattern)){if(keywordKinds[part]){const mark=document.createElement('mark');mark.className=`keyword keyword-${keywordKinds[part]}`;mark.textContent=part;frag.append(mark);}else frag.append(part);}node.replaceWith(frag);keywordPattern.lastIndex=0;}});}
let student;
try {student=restoreSession(sessionStorage.getItem(STORAGE_KEY));}catch {student=newSession();}
let teacher=false, teacherSession=newSession(), route='home', drafts={}, toastTimer;
let prediction={}, drops={}, unknown={}, nutrient='carbs';
const active=()=>teacher?teacherSession:student;
function commit(s){if(teacher){teacherSession=s;return;} student=s;try{sessionStorage.setItem(STORAGE_KEY,JSON.stringify(student));}catch{notify('目前無法保留本次開啟期間的紀錄。');}}
function notify(text){const el=$('#score-toast');el.textContent=text;el.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>{el.hidden=true;},4200);}
function accessible(page){return courses.some(c=>c[0]===page);}
function syncChrome(){
  const session=active(),activityDone={challenge1:['formative1','game1'],challenge2:['formative2','game2'],finalchallenge:['summative','hero']};
  $('#mode-label').innerHTML=teacher?' <strong>教師瀏覽</strong> <button id="teacher-exit" type="button">結束瀏覽</button>':'';
  $('#identity-label').textContent='';
  $('#learning-nav').hidden=false;document.body.classList.toggle('course-page',route!=='home');
  $('#progress').innerHTML=courses.map(([id,title],i)=>{const done=id==='home'?Boolean(session.introDone):learningIds.includes(id)?lessonDone(session,id):activityDone[id]?activityDone[id].every(x=>session.activities[x]?.length):id==='results'?Boolean(session.submission):false;return `<button type="button" data-page="${id}" ${route===id?'aria-current="step"':''} aria-label="第 ${i+1} 頁，${title}${done?'，已完成':''}"><span class="step-symbol" aria-hidden="true">${done?'✓':route===id?'●':'○'}</span><span><small>第 ${i+1} 頁</small>${title}</span></button>`;}).join('');
  $('#nav-score-value').textContent=`${totalScore(session)}／150`;
  const current=$('#progress [aria-current]');if(current)$('#progress').scrollLeft=current.offsetLeft-$('#progress').offsetLeft-$('#progress').clientWidth/2+current.offsetWidth/2;
}
function navigate(page){if(!accessible(page)){notify('先完成導讀的兩個暖身問題，就能進入碘液學習頁。');return;} if(location.hash===`#${page}`)render();else location.hash=page;}
function render(){
  const hash=location.hash.slice(1);route=courses.some(c=>c[0]===hash)?hash:'home';stopActivity();questions=route==='iodine'?iodineQuestions:(lessons[route]?.questions||[]);
  document.title=`${courses.find(c=>c[0]===route)[1]}｜食物中的養分與能量`;
  $('#main').innerHTML=route==='home'?homeView():route==='iodine'?lessonView():lessons[route]?genericLessonView(lessons[route]):renderActivity(route,{active,commit,sync:syncChrome,teacher:()=>teacher,render,colorize:colorizeKeywords});
  syncChrome();
  if(learningIds.includes(route)){initDrafts();questions.forEach(renderQuestion);updateLessonFooter();refreshExplorations();}
  colorizeKeywords();
  window.scrollTo({top:0,behavior:'instant'});
  $('#main').focus({preventScroll:true});
}
function homeView(){
  return `<section class="hero"><div class="hero-copy"><p class="eyebrow">從每天吃的食物開始</p><h1>每一口，<br>都有小秘密。</h1><p class="hero-lead">認識養分、操作檢測，再用證據說出合理結論。</p><div class="topic-tags"><span>15 頁學習旅程</span><span>互動探索</span><span>多元評量</span></div><a class="primary hero-start" href="#home-warmup">一起看看吧 <span aria-hidden="true">→</span></a></div><figure class="hero-picture"><img src="assets/food-table.png" alt="餐盤上有米飯、雞蛋、豆腐、青菜與番茄，旁邊有水與一瓣橘子。" width="1536" height="1024"><figcaption>一份餐點，可以帶來不只一種養分。</figcaption></figure></section>
  <section class="journey colorful-journey" aria-label="三階段學習旅程"><article><span>01</span><div><h3>認識養分</h3><p>比較六大養分的供能、構成與調節任務。</p></div></article><article><span>02</span><div><h3>實驗找證據</h3><p>先預測、再操作，讀懂碘液與本氏液反應。</p></div></article><article><span>03</span><div><h3>整合與成果</h3><p>完成紙張探究、綜合挑戰，最後再填基本資料。</p></div></article></section>
  <section class="paper home-warmup" id="home-warmup"><div class="section-heading"><div><p class="eyebrow">出發前暖身</p><h2>一口食物，可能帶來什麼？</h2></div><span class="badge">不計分</span></div><p>植物可自行製造養分；動物主要透過攝食獲得養分。同一份食物也可能含有多種養分。</p>${active().introDone?'<div class="feedback correct"><strong>暖身已完成。</strong><p>進度會保留到這次課程分頁關閉為止。</p></div>':`<form id="intro-form"><fieldset><legend>同一份食物，有可能含有不只一種養分嗎？</legend><div class="options"><label><input type="radio" name="mix" value="yes">有可能</label><label><input type="radio" name="mix" value="no">不可能</label></div></fieldset><button class="primary" type="submit" id="intro-check" disabled>看看說明</button></form><div id="intro-feedback" role="status" hidden></div>`}<div class="form-actions"><button class="primary" id="home-start" type="button" data-page="nutrients" ${active().introDone||teacher?'':'disabled'}>${demoProgress(student)>0?'繼續學習':'開始第 2 頁'} →</button>${demoProgress(student)>0?'<button class="quiet" id="restart" type="button">清除進度，重新練習</button>':''}</div><p class="small">共 15 頁。基本資料會在完成全部內容後，於最後一頁輸入。</p></section>
  <div class="home-teacher"><button class="quiet" id="home-teacher-open" type="button">教師瀏覽入口</button><span class="small">自由檢視本次已製作的頁面</span></div>`;
}
const nutrients={carbs:['醣類','可供能，也有構成的例子','澱粉是醣類的一員；纖維素也是醣類，參與構成植物細胞壁。可供能的類別，不代表每個成員都能被人體同樣利用。'],protein:['蛋白質','可供能，也參與構成身體','毛髮與肌肉都含有蛋白質。它的工作不只是「長肌肉」。'],fat:['脂質','可供能，也有保溫等功能','皮下脂質有助減少熱量散失，也可作為能量來源。'],water:['水','不供能，仍是必要養分','許多物質需溶於水，才能參與細胞內的反應。'],minerals:['礦物質','不供能，也參與構成與運作','鈣、磷是骨骼與牙齒的重要成分；鐵與造血有關。'],vitamins:['維生素','不供能，協助生理功能','維生素有助調節生理機能，不能只用是否有熱量來判斷營養價值。']};
function introView(){return `<div class="page-heading"><p class="eyebrow">先想一想</p><h1>一口食物，帶來什麼？</h1><p>從熟悉的餐點，認識身體需要的養分。</p></div>
  <section class="two-col"><article class="paper"><h2>有熱量，就代表什麼營養都有嗎？</h2><p>生物需要養分維持生命。植物可自行製造養分；動物則主要透過攝食其他生物獲取養分。取得方式不同，卻都需要養分。</p><p>養分可以<strong>提供能量</strong>、<strong>參與構成身體</strong>，或<strong>協助正常生理運作</strong>。這些工作不是互斥的，一種養分可能有多種功能。</p><p>食物和養分也不相同。一份食物通常包含多種養分，不能只看照片就判定它的完整成分。</p></article><figure class="paper intro-picture"><img src="assets/food-table.png" alt="包含米飯、雞蛋、豆腐、蔬菜、水和水果的餐點插圖；圖片只作情境，不是成分檢測結果。" width="1536" height="1024"><figcaption>食物是來源，養分是其中的成分。</figcaption><button class="quiet" type="button" data-zoom="food">放大看餐點</button></figure></section>
  <section class="paper"><div class="section-heading"><h2>六大養分，各有任務</h2><span class="small">點一張卡，看看它的工作</span></div><div class="nutrient-grid" aria-label="養分功能探索">${Object.entries(nutrients).map(([id,[name]])=>`<button type="button" class="nutrient" data-nutrient="${id}" aria-pressed="${nutrient===id}"><span>${name}</span><small>${['carbs','protein','fat'].includes(id)?'可供能':'不供能'}</small></button>`).join('')}</div><div id="nutrient-detail" class="soft detail" aria-live="polite"></div><p class="small">接下來會逐一比較養分的功能，並用實驗檢查食物中的成分。</p></section>
  <section class="paper"><div class="section-heading"><h2>先暖暖身</h2><span class="badge">不計分，答錯也能繼續</span></div><form id="intro-form"><fieldset><legend>1．植物和動物獲取養分的方式完全相同嗎？</legend><div class="options">${shuffle([['same','完全相同'],['different','不完全相同']]).map(([v,t])=>`<label><input type="radio" name="source" value="${v}">${t}</label>`).join('')}</div></fieldset><fieldset><legend>2．同一份食物，有可能含有不只一種養分嗎？</legend><div class="options">${shuffle([['yes','有可能，同一食物可含多種養分'],['no','不可能，每種食物只有一種養分']]).map(([v,t])=>`<label><input type="radio" name="mix" value="${v}">${t}</label>`).join('')}</div></fieldset><button class="primary" type="submit" id="intro-check" disabled>看看說明</button></form><div id="intro-feedback" role="status" hidden></div></section>
  <div class="page-nav"><a class="quiet" href="#home">← 回首頁</a><div><p id="intro-next-hint" class="small">${active().introDone||teacher?'可以繼續認識六大養分。':'兩題都作答，並查看說明後，就能繼續。'}</p><button id="intro-next" class="primary" type="button" data-page="nutrients" ${active().introDone||teacher?'':'disabled'}>前往：六大養分，各有任務 →</button></div></div>`;}
function renderNutrient(){const [name,title,body]=nutrients[nutrient];$('#nutrient-detail').innerHTML=`<strong>${name}：${title}</strong><p>${body}</p>`;document.querySelectorAll('[data-nutrient]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.nutrient===nutrient)));}

function dishSVG(id,description,fill='#f7faf6'){
  return `<svg viewBox="0 0 210 140" role="img" aria-label="${esc(description)}" class="dish-diagram"><path d="M93 13l13-5 21 49-13 5z" fill="#ddd4bc" stroke="#827864" stroke-width="2"/><path d="M95 14l9-4 6 14-9 4z" fill="#6c6253"/><path d="M116 62c-8 11-9 18-1 18s10-7 1-18z" class="drop" fill="#b18a37" opacity="0"/><path d="M24 107v9c0 23 162 23 162 0v-9" fill="#dce5db" stroke="#93a697" stroke-width="2"/><ellipse cx="105" cy="106" rx="81" ry="23" fill="#edf1e8" stroke="#93a697" stroke-width="2"/><ellipse id="${id}" cx="105" cy="106" rx=" sixty" ry="17" fill="${fill}"/></svg>`.replace('rx=" sixty"','rx="65"');
}
function sampleHTML(id,title){return `<article class="sample-card"><h3>${title}</h3>${dishSVG(`liquid-${id}`,`${title}，尚未滴入碘液`)}<p id="color-${id}" class="color-label">尚未滴加</p><button class="secondary" type="button" data-drop="${id}" disabled>滴加到${title}</button></article>`;}
function taskGuide(goal,steps,cue){return `<div class="task-brief"><div><span>任務目標</span><h3>${goal}</h3><p>${cue}</p></div><ol class="task-steps">${steps.map((s,i)=>`<li><b>${i+1}</b><span>${s}</span></li>`).join('')}</ol></div>`;}
function lessonView(){
  prediction={};drops={};unknown={};
  return `<div class="page-heading"><p class="eyebrow">動手找線索</p><h1>碘液找出澱粉</h1><p>一滴試劑，兩份樣本。先觀察，再下結論。</p><div class="lesson-jumps"><a href="#concept">先認識</a><a href="#explore">試著觀察</a><a href="#practice">換你試試</a></div></div>
  <section class="paper" id="concept"><div class="section-heading"><h2><span class="section-number">1</span> 先認識</h2><span class="small">方法與證據</span></div><div class="two-col concept-layout"><div><p><mark>澱粉</mark>是醣類的一員，米飯等食物中常含有澱粉。若想知道樣本中是否有澱粉，可以用<mark>碘液</mark>檢測，而不是只憑食物外觀或甜味猜測。</p><p>碘液原本是<strong class="brown-text">黃褐色</strong>。加入澱粉液後，可能呈現<strong class="purple-text">藍黑色或紫紅色</strong>；滴入水中，則維持碘液的黃褐色。本課這項檢測<strong>不需要加熱</strong>。</p><p>將水與已知澱粉液作比較，可以先認識陰性與陽性的顏色。檢測未知樣本時，先記錄「顏色如何改變」，再根據比較形成結論。</p></div><div class="method-diagram" role="img" aria-label="檢測流程：樣本加碘液，不需加熱，觀察顏色；藍黑色或紫紅色支持檢出澱粉。"><span>樣本</span><b>＋</b><span class="reagent">碘液<small>黃褐色</small></span><div class="method-arrow">↓ 不需加熱</div><span class="outcome">觀察顏色<small>藍黑色／紫紅色</small></span><div class="method-arrow">↓ 比較已知樣本</div><span class="conclusion">支持檢出澱粉</span></div></div><aside class="callout"><strong>先分清楚兩件事</strong><br>「變成藍黑色」是觀察；「檢出澱粉」是由觀察與比較支持的結論。檢出澱粉，也不代表樣本只有澱粉。</aside></section>
  <section class="paper exploration exploration-tone-3" id="explore"><div class="section-heading exploration-heading"><div><span class="exploration-number">1</span><span class="zone-kicker">互動探索</span><h2>建立碘液顏色判讀尺</h2></div><span class="badge">教學模擬・可重播</span></div>${taskGuide('用水與已知澱粉液，建立陰性和陽性的顏色基準。',['先觀察兩份樣本原本的顏色','預測加入碘液後的顏色','滴加並比較實際結果'],'先分清楚樣本原本的顏色與加入碘液後的變化；預測不計分。')}<div class="activity-zone initial-sample-zone"><div class="zone-title"><span>步驟一：先觀察樣本</span><small>這是尚未加入碘液時的樣子</small></div><div class="initial-sample-grid"><article><span class="sample-swatch clear"></span><div><strong>水</strong><p>無色透明</p></div></article><article><span class="sample-swatch white"></span><div><strong>澱粉液</strong><p>白色、略混濁</p></div></article></div><p class="callout"><strong>觀察提醒：</strong>先記住樣本原本的顏色，再預測加入黃褐色碘液後會不會改變。</p></div><div class="activity-zone"><div class="zone-title"><span>步驟二：再預測</span><small>兩個預測完成後，滴加按鈕才會開啟</small></div><div class="prediction-row">${[['water','水'],['starch','澱粉液']].map(([id,label])=>`<label class="field">${label}＋碘液，你預測會……<select data-predict="${id}" aria-label="預測${label}的顏色"><option value="">請選擇</option><option value="brown">呈黃褐色</option><option value="positive">呈藍黑色或紫紅色</option><option value="clear">呈無色透明</option><option value="white">呈白色</option></select></label>`).join('')}</div></div><div class="activity-zone observation-zone"><div class="zone-title"><span>步驟三：滴加並觀察</span><small>請比較兩個培養皿的顏色</small></div><div class="experiment-board">${sampleHTML('water','水')}${sampleHTML('starch','澱粉液')}</div><p id="poe-feedback" class="callout" role="status">先完成兩個預測，就可以滴加。預測不計分，可以放心嘗試。</p><button class="quiet" type="button" id="reset-experiment">重新觀察</button></div>
  <div class="unknown-box"><div class="section-heading exploration-heading"><div><span class="exploration-number">2</span><span class="zone-kicker">再應用</span><h2>破解未知樣本 A</h2></div></div>${taskGuide('把剛建立的顏色基準，用在未知樣本 A。',['讓 A 與水對照接受相同操作','比較兩份樣本的實際顏色','選出證據真正支持的結論'],'只判斷本次碘液檢測能回答的問題；其他養分仍需要其他證據。')}<div class="activity-zone observation-zone"><div class="zone-title"><span>同步檢測</span><small>一次按下按鈕，兩份樣本接受相同操作</small></div><div class="unknown-samples"><div>${dishSVG('unknown-control','水對照，尚未滴加')}<strong>水對照</strong><span id="unknown-control-label">尚未滴加</span></div><div>${dishSVG('unknown-a','未知樣本 A，尚未滴加')}<strong>樣本 A</strong><span id="unknown-a-label">尚未滴加</span></div></div><button id="unknown-test" class="secondary" type="button">同時滴加並觀察</button><div id="unknown-reasoning" hidden><p>水呈黃褐色，A 呈藍黑色。選出資料支持的說法。</p><div class="options"><button type="button" data-unknown-answer="limited">A 檢出澱粉，其他成分仍需另找證據</button><button type="button" data-unknown-answer="only">A 只有澱粉，沒有其他養分</button></div><p id="unknown-feedback" role="status"></p></div></div><p class="completion-cue"><strong>完成線索：</strong>能用水對照與顏色變化支持「A 檢出澱粉」，並保留其他成分未知。</p></div></section>
  <section class="paper practice-section" id="practice"><div class="section-heading"><h2><span class="section-number">3</span> 換你試試</h2><span id="practice-count" class="badge"></span></div><p>五題都答對就完成本頁。每題第一次答對得 3 分，第二次 2 分，第三次起 1 分；答錯後可以看解析再試。</p><div class="score-strip"><span>本頁／本頁學習分數</span><strong id="score-total"></strong></div><div id="question-list">${questions.map(q=>`<article id="${q.id}" class="question"></article>`).join('')}</div></section>
  <section class="completion-card" id="completion-card" hidden></section><div class="page-nav"><a class="quiet" href="#challenge1">← 回看養分挑戰站</a><div><p id="lesson-next-hint" class="small"></p><button class="primary" id="lesson-finish" type="button" disabled>查看本次成果 →</button></div></div>`;
}
function initDrafts(){drafts={};for(const q of questions)resetDraft(q);}
function resetDraft(q){drafts[q.id]={answer:['order','multiple'].includes(q.kind)?[]:['single','boolean'].includes(q.kind)?null:{},status:'editing',selectedRow:null,order:shuffle(q.options||[]),rows:shuffle(q.rows||[]),groups:Object.fromEntries(Object.entries(q.groups||{}).map(([k,v])=>[k,shuffle(v)]))};}
function answerSummary(q){if(q.kind==='fill')return q.rows.map(([k,t])=>`${t}：${q.answer[k]}`).join('；');if(typeof q.answer==='string')return q.options.find(o=>o[0]===q.answer)[1];if(Array.isArray(q.answer))return q.answer.map(v=>q.options.find(o=>o[0]===v)[1]).join(' → ');return q.rows.map(([k,label])=>`${label}：${(q.groups?.[k]||q.options).find(o=>o[0]===q.answer[k])[1]}`).join('；');}
function questionGraphic(q){
 const diagram=q.id.startsWith('proteinfat')?`<svg viewBox="0 0 500 280" role="img" aria-label="身體構造標記：① 毛髮，② 肌肉，③ 皮下脂質"><circle cx="170" cy="50" r="28" fill="#e7c9ac"/><path d="M142 40Q170 0 198 40" stroke="#5e5a45" stroke-width="14" fill="none"/><path d="M170 80V190M167 97L115 161M173 97L226 161M168 185L135 258M173 185L205 258" stroke="#92a880" stroke-width="26" stroke-linecap="round"/><rect x="150" y="90" width="40" height="83" rx="15" fill="#e9b95f"/><g fill="#436447" font-size="20"><text x="290" y="40">① 毛髮</text><text x="290" y="145">② 肌肉</text><text x="290" y="213">③ 皮下脂質</text></g><g stroke="#73896b" fill="none" stroke-width="2"><path d="M190 25L275 30"/><path d="M219 148L275 138"/><path d="M185 150L245 205H275"/></g></svg>`:q.id.startsWith('nutrients')?`<svg viewBox="0 0 500 270" role="img" aria-label="虛構餐點及已提供的四項成分：① 水、② 澱粉、③ 蛋白質、④ 脂質"><ellipse cx="245" cy="140" rx="165" ry="105" fill="#e9edda" stroke="#97aa85" stroke-width="3"/><ellipse cx="245" cy="140" rx="130" ry="80" fill="#fffdf4"/><path d="M145 145Q140 65 230 100L245 170Z" fill="#e4d5aa"/><ellipse cx="295" cy="135" rx="38" ry="46" fill="#f9eed0"/><circle cx="295" cy="135" r="22" fill="#edbd5f"/><path d="M225 195Q230 140 265 165Q305 177 285 210Z" fill="#94ad6b"/><g font-size="18" fill="#365d3d"><text x="15" y="30">① 水</text><text x="15" y="250">② 澱粉</text><text x="350" y="30">③ 蛋白質</text><text x="380" y="250">④ 脂質</text></g><g stroke="#78946b"><path d="M75 32L150 88M95 232L170 167M371 40L307 91M390 227L313 186"/></g></svg>`:`<svg viewBox="0 0 500 250" role="img" aria-label="功能網：① 溶解與反應、② 骨骼牙齒、③ 生理調節"><g stroke="#a1b293" stroke-width="3"><path d="M250 105L90 190M250 105L250 190M250 105L410 190"/></g><rect x="170" y="35" width="160" height="65" rx="20" fill="#436447"/><text x="250" y="75" text-anchor="middle" fill="white" font-size="21">必要功能</text><g fill="#eef2df" stroke="#a1b293">${[90,250,410].map(x=>`<circle cx="${x}" cy="180" r="60"/>`).join('')}</g><g text-anchor="middle" fill="#436447" font-size="17"><text x="90" y="175">① 溶解物質</text><text x="90" y="200">參與反應</text><text x="250" y="187">② 骨骼牙齒</text><text x="410" y="187">③ 生理調節</text></g></svg>`;
 return `<figure class="question-graphic">${diagram}<figcaption>教學示意；依題目明示資料作答，不表示構造只有單一成分。</figcaption></figure>`;
}
function evidenceDiagram(){return `<figure class="evidence-diagram"><div><span class="observation-dot brown"></span><strong>水對照</strong><span>黃褐色</span></div><div><span class="observation-dot purple"></span><strong>樣本 C</strong><span>紫紅色</span></div><figcaption>相同條件滴入碘液後的模擬紀錄</figcaption></figure>`;}
function renderQuestion(q,focusId){
  const d=drafts[q.id], saved=active().questions[q.id], done=Boolean(saved?.completed), locked=done||d.status==='wrong';
  let controls='';
  if(done&&d.status!=='correct'){
    controls=`<p class="completed-message">✓ 此題已完成，保留 ${saved.points} 分。</p><details><summary>查看答案與解析</summary><p>${answerSummary(q)}</p><p>${q.explanation}</p></details>`;
  }else{
    if(['single','boolean'].includes(q.kind))controls=`<fieldset class="answer-fieldset" ${locked?'disabled':''}><legend class="sr-only">${q.title}</legend><div class="options">${d.order.map(([id,label])=>`<label><input type="radio" name="${q.id}" data-answer="${q.id}" value="${id}" ${d.answer===id?'checked':''}>${label}</label>`).join('')}</div></fieldset>`;
    if(q.kind==='match')controls=`<div class="match-grid"><div><p class="small">① 選項目</p>${d.rows.map(([id,label])=>`<button id="${q.id}-row-${id}" type="button" class="match-row" data-match-row="${q.id}" data-value="${id}" aria-pressed="${d.selectedRow===id}" ${locked?'disabled':''}><strong>${label}</strong><span>${d.answer[id]?q.options.find(o=>o[0]===d.answer[id])[1]:'尚未配對'}</span></button>`).join('')}</div><div><p class="small">② 配對概念</p>${d.order.map(([id,label])=>`<button id="${q.id}-target-${id}" type="button" class="match-target" data-match-target="${q.id}" data-value="${id}" ${locked||!d.selectedRow?'disabled':''}>${label}</button>`).join('')}</div></div><p class="small" aria-live="polite">${d.selectedRow?`正在配對：${q.rows.find(r=>r[0]===d.selectedRow)[1]}`:'請先點選一個項目。'}</p>`;
    if(q.kind==='order')controls=`<div class="order-slots" aria-label="已排列的步驟">${q.options.map((_,i)=>d.answer[i]?`<button type="button" id="${q.id}-remove-${d.answer[i]}" data-order-remove="${q.id}" data-value="${d.answer[i]}" ${locked?'disabled':''}><span>${i+1}</span>${q.options.find(o=>o[0]===d.answer[i])[1]}<small>撤回</small></button>`:`<div class="order-empty"><span>${i+1}</span>下一步放這裡</div>`).join('')}</div><div class="order-bank" aria-label="待排列的步驟">${d.order.map(([id,label])=>`<button id="${q.id}-add-${id}" type="button" class="secondary" data-order-add="${q.id}" data-value="${id}" ${locked||d.answer.includes(id)?'disabled':''}>${label}</button>`).join('')}</div>`;
    if(['evidence','repair','diagram','decision'].includes(q.kind))controls=(q.id==='iodine-5'?evidenceDiagram():q.kind==='diagram'?questionGraphic(q):'')+`<fieldset class="answer-fieldset evidence-fields" ${locked?'disabled':''}><legend class="sr-only">${q.label}</legend>${q.rows.map(([id,label])=>`<label class="field">${label}<select data-evidence="${q.id}" data-part="${id}"><option value="">請選擇</option>${(d.groups[id]||d.order).map(([v,t])=>`<option value="${v}" ${d.answer[id]===v?'selected':''}>${t}</option>`).join('')}</select></label>`).join('')}</fieldset>`;

    if(q.kind==='multiple')controls=`<fieldset class="answer-fieldset" ${locked?'disabled':''}><legend class="sr-only">選出所有正確選項</legend><div class="options">${d.order.map(([id,label])=>`<label><input type="checkbox" data-multiple="${q.id}" value="${id}" ${d.answer.includes(id)?'checked':''}>${label}</label>`).join('')}</div></fieldset>`;
    if(q.kind==='fill')controls=`<fieldset class="answer-fieldset" ${locked?'disabled':''}><legend class="sr-only">填入關鍵詞</legend>${q.rows.map(([id,label])=>`<label class="field">${label}<select data-fill="${q.id}" data-part="${id}"><option value="">請選詞卡</option>${(d.groups[id]||d.order).map(([v,t])=>`<option value="${v}" ${d.answer[id]===v?'selected':''}>${t}</option>`).join('')}</select></label>`).join('')}</fieldset>`;
    if(q.id==='benedict-3'&&controls)controls=`<figure class="evidence-diagram"><div><span class="observation-dot" style="background:#7b9d55"></span><strong>綠色</strong></div><div><span class="observation-dot" style="background:#df9637"></span><strong>橙色</strong></div><div><span class="observation-dot" style="background:#bd5038"></span><strong>紅色</strong></div><figcaption>同體積、同試劑量、相同加熱條件的模擬紀錄</figcaption></figure>`+controls;
    const feedback=d.status==='wrong'?`<div class="feedback incorrect" role="status"><strong>再想一想，這次尚未答對。</strong><p>${q.explanation}</p><button class="secondary" data-retry="${q.id}" type="button">重新作答</button></div>`:d.status==='correct'?`<div class="feedback correct" role="status"><strong>答對了！本題＋${saved.points} 分。</strong><p>${q.explanation}</p><p class="question-score">累積學習總分 ${totalScore(active())}／150</p></div>`:'';
    controls+=`<div class="question-actions"><button class="secondary" id="${q.id}-check" type="button" data-check="${q.id}" ${locked||!isComplete(q,d.answer)?'disabled':''}>檢查答案</button><span class="small">${done?`第 ${saved.attempts} 次答對`:d.status==='wrong'?`第 ${saved.attempts} 次尚未答對`:`本次為第 ${(saved?.attempts||0)+1} 次作答`}</span></div>${feedback}`;
  }
  const container=document.getElementById(q.id);
  container.className=`question${done?' correct':d.status==='wrong'?' incorrect':''}`;
  container.innerHTML=`<p class="eyebrow">${String(questions.indexOf(q)+1).padStart(2,'0')} ${q.label}</p><h3>${q.title}</h3><p class="question-instruction">${q.instruction}</p>${controls}`;
  if(focusId)document.getElementById(focusId)?.focus({preventScroll:true});
}
function enableCheck(id){const q=questions.find(q=>q.id===id);document.getElementById(`${id}-check`).disabled=!isComplete(q,drafts[id].answer);}
function updateLessonFooter(){if(!learningIds.includes(route))return;const s=active(),count=completedCount(s,route);$('#score-total').textContent=`${pageScore(s,route)}／15`;document.querySelectorAll('.question-score').forEach(el=>el.textContent=`累積學習總分 ${totalScore(s)}／150`);$('#practice-count').textContent=`${count}／5 題完成`;const next=courses[courses.findIndex(c=>c[0]===route)+1];$('#lesson-finish').disabled=false;$('#lesson-finish').textContent=`下一頁：${next[1]} →`;$('#lesson-next-hint').textContent=lessonDone(s,route)?'五題都完成了，學習分數已保留。':`還有 ${5-count} 題未完成；審閱版可先自由瀏覽。`;syncChrome();}
function showResults(){navigate(courses[courses.findIndex(c=>c[0]===route)+1][0]);}
function genericLessonView(l){const previous=courses[courses.findIndex(c=>c[0]===l.id)-1];return `<div class="page-heading"><p class="eyebrow">認識、探索，再用證據說明</p><h1>${l.title}</h1><p>${l.lead}</p><div class="lesson-jumps"><a href="#concept">先認識</a><a href="#explore">互動探索</a><a href="#practice">五種評量</a></div></div><section class="paper" id="concept"><h2>先認識</h2><div class="two-col"><div>${l.paragraphs.map(t=>`<p>${t}</p>`).join('')}</div><figure class="concept-map" aria-label="${l.title}的概念圖">${l.diagram.map((t,i)=>`<div class="concept-node ${i?'':'main-node'}">${t}</div>`).join('')}<figcaption>概念示意，依本課教材整理。</figcaption></figure></div></section><div id="explore">${renderExplorations(l.explorations)}</div><section class="paper practice-section" id="practice"><div class="section-heading"><h2>換你試試：五種多元評量</h2><span id="practice-count" class="badge"></span></div><p>所有題目一次呈現。每題第一次答對 3 分、第二次 2 分、第三次起 1 分。答錯可看解析再試；本頁滿分 15 分。</p><div class="score-strip"><span>本頁學習分數</span><strong id="score-total"></strong></div><div id="question-list">${questions.map(q=>`<article id="${q.id}" class="question"></article>`).join('')}</div></section><div class="page-nav"><a class="quiet" href="#${previous[0]}">← ${previous[1]}</a><div><p id="lesson-next-hint" class="small"></p><button class="primary" id="lesson-finish" type="button">下一頁</button></div></div>`;}
function predictionAnalysis(){
  const waterRight=prediction.water==='brown',starchRight=prediction.starch==='positive';
  const waterNote=waterRight
    ?'<strong>水的預測符合觀察：</strong>水不含澱粉，加入碘液後仍呈黃褐色，可作為沒有澱粉反應的比較基準。'
    :'<strong>水的預測需要修正：</strong>水中沒有澱粉可和碘液產生藍黑色或紫紅色反應，因此碘液維持原本的黃褐色。';
  const starchNote=starchRight
    ?'<strong>澱粉液的預測符合觀察：</strong>已知澱粉液加入碘液後呈藍黑色，建立了檢出澱粉的顏色基準。'
    :'<strong>澱粉液的預測需要修正：</strong>澱粉會和碘液產生特徵性的藍黑色或紫紅色，因此不會維持黃褐色。';
  return `<strong>${waterRight&&starchRight?'兩項預測都符合觀察。':'預測和觀察有差異，請逐項比較。'}</strong><ul><li>${waterNote}</li><li>${starchNote}</li></ul><p><strong>判讀範圍：</strong>這組顏色只能作為澱粉的檢測線索，不能用來判斷蛋白質、脂質或其他所有養分。</p>`;
}
function dropSample(id){if(!prediction.water||!prediction.starch||drops[id])return;drops[id]=true;const positive=id==='starch';document.getElementById(`liquid-${id}`).setAttribute('fill',positive?'#3e3352':'#b68b34');const svg=document.getElementById(`liquid-${id}`).closest('svg');svg.setAttribute('aria-label',`${positive?'澱粉液':'水'}滴加碘液後，${positive?'呈藍黑色':'呈黃褐色'}`);svg.classList.add('dropped');document.getElementById(`color-${id}`).textContent=positive?'呈藍黑色':'呈黃褐色';document.querySelector(`[data-drop="${id}"]`).disabled=true;document.querySelector(`[data-predict="${id}"]`).disabled=true;
  if(drops.water&&drops.starch){$('#poe-feedback').innerHTML=predictionAnalysis();colorizeKeywords();}else $('#poe-feedback').textContent='一份樣本完成了。請再滴加另一份，才能比較兩個結果。';
}
function resetExperiment(){prediction={};drops={};document.querySelectorAll('[data-predict]').forEach(s=>{s.value='';s.disabled=false;});document.querySelectorAll('[data-drop]').forEach(b=>b.disabled=true);for(const id of ['water','starch']){const liquid=document.getElementById(`liquid-${id}`);liquid.setAttribute('fill','#f7faf6');liquid.closest('svg').classList.remove('dropped');liquid.closest('svg').setAttribute('aria-label',`${id==='water'?'水':'澱粉液'}，尚未滴入碘液`);document.getElementById(`color-${id}`).textContent='尚未滴加';}$('#poe-feedback').textContent='先完成兩個預測，就可以滴加。預測不計分，可以放心嘗試。';}

document.addEventListener('change',e=>{
  const t=e.target;
  if(t.closest('#intro-form'))$('#intro-check').disabled=!$('#intro-form input[name="mix"]:checked');
  if(t.dataset.expInput)refreshExplorations();
  if(t.dataset.multiple){const d=drafts[t.dataset.multiple];d.answer=[...document.querySelectorAll(`[data-multiple="${t.dataset.multiple}"]:checked`)].map(x=>x.value);enableCheck(t.dataset.multiple);}
  if(t.dataset.fill){drafts[t.dataset.fill].answer[t.dataset.part]=t.value;enableCheck(t.dataset.fill);}
  if(t.dataset.predict){prediction[t.dataset.predict]=t.value;document.querySelectorAll('[data-drop]').forEach(b=>b.disabled=!prediction.water||!prediction.starch||Boolean(drops[b.dataset.drop]));}
  if(t.dataset.answer){drafts[t.dataset.answer].answer=t.value;enableCheck(t.dataset.answer);}
  if(t.dataset.evidence){drafts[t.dataset.evidence].answer[t.dataset.part]=t.value;enableCheck(t.dataset.evidence);}
});
document.addEventListener('input',e=>{const t=e.target;if(t.dataset.fill){drafts[t.dataset.fill].answer[t.dataset.part]=t.value;enableCheck(t.dataset.fill);}});
document.addEventListener('submit',e=>{
  if(e.target.id==='intro-form'){e.preventDefault();const data=new FormData(e.target);if(!data.has('mix'))return;const right=data.get('mix')==='yes';$('#intro-feedback').hidden=false;$('#intro-feedback').className='feedback correct';$('#intro-feedback').innerHTML=`<strong>暖身完成，帶著問題出發。</strong><p>${right?'你的判斷正確。':'可以這樣修正：'}同一份食物可同時含多種養分，例如水和澱粉可以一起存在於一份餐點中。</p>`;e.target.querySelectorAll('input,button').forEach(el=>el.disabled=true);commit({...active(),introDone:true});$('#home-start').disabled=false;syncChrome();colorizeKeywords();}
  if(e.target.id==='teacher-form'){e.preventDefault();if($('#teacher-password').value!=='55688'){$('#teacher-error').textContent='密碼不正確，請再試一次。';return;}teacher=true;teacherSession=newSession();$('#teacher-dialog').close();$('#teacher-password').value='';$('#teacher-error').textContent='';navigate('nutrients');}
});
document.addEventListener('click',e=>{
  const b=e.target.closest('button');if(!b||b.disabled)return;
  if(b.hasAttribute('data-close'))b.closest('dialog').close();
  if(b.dataset.page){navigate(b.dataset.page);b.closest('dialog')?.close();}
  if(b.id==='teacher-open'||b.id==='home-teacher-open'){$('#teacher-dialog').showModal();$('#teacher-password').focus();}
  if(b.id==='teacher-exit'){teacher=false;teacherSession=newSession();navigate('home');}
  if(b.id==='map-open'){$('#map-items').innerHTML=courses.map(([id,title],i)=>`<button type="button" ${id==='future'?'disabled':`data-page="${id}"`}><span>${String(i+1).padStart(2,'0')}</span>${title}<small>${id==='future'?'後續製作':accessible(id)?'自由瀏覽':'完成導讀後解鎖'}</small></button>`).join('');$('#map-dialog').showModal();}
  if(b.id==='nav-scroll-left')$('#progress').scrollBy({left:-Math.max(320,$('#progress').clientWidth*.7),behavior:'smooth'});
  if(b.id==='nav-scroll-right')$('#progress').scrollBy({left:Math.max(320,$('#progress').clientWidth*.7),behavior:'smooth'});
  if(b.id==='restart'){if(confirm('要清除本次開啟期間的分數與進度，重新練習嗎？')){commit(newSession());render();}}
  if(b.dataset.nutrient){nutrient=b.dataset.nutrient;renderNutrient();}
  if(b.dataset.zoom==='food'){$('#image-title').textContent='一份餐點，多種養分';$('#image-content').innerHTML='<img src="assets/food-table.png" alt="完整餐盤與水杯、水果的原創插圖。"><p>插圖只作情境，不能憑外觀判定完整成分。</p>';$('#image-dialog').showModal();}
  if(b.dataset.drop)dropSample(b.dataset.drop);
  if(b.id==='reset-experiment')resetExperiment();
  if(b.id==='unknown-test'){unknown.tested=true;for(const [id,color,label] of [['control','#b68b34','黃褐色'],['a','#3e3352','藍黑色']]){const el=document.getElementById(`unknown-${id}`);el.setAttribute('fill',color);el.closest('svg').classList.add('dropped');el.closest('svg').setAttribute('aria-label',`${id==='control'?'水對照':'樣本 A'}，滴入碘液後呈${label}`);document.getElementById(`unknown-${id}-label`).textContent=label;}b.disabled=true;$('#unknown-reasoning').hidden=false;}
  if(b.dataset.unknownAnswer&&unknown.tested){const good=b.dataset.unknownAnswer==='limited';$('#unknown-feedback').className=`feedback ${good?'correct':'incorrect'}`;$('#unknown-feedback').textContent=good?'有證據的結論！A 檢出澱粉，其他成分還不能靠這個實驗確定。':'這個推論超過了證據範圍。碘液只能提供澱粉線索，沒有檢測所有其他養分。再選一次，縮小結論的範圍。';}
  const qid=b.dataset.matchRow||b.dataset.matchTarget||b.dataset.orderAdd||b.dataset.orderRemove||b.dataset.check||b.dataset.retry;
  if(qid){const q=questions.find(q=>q.id===qid),d=drafts[qid];if(!q||!d||active().questions[qid]?.completed)return;
    if(b.dataset.retry){resetDraft(q);renderQuestion(q,`${q.id}-check`);return;}
    if(d.status!=='editing')return;
    if(b.dataset.matchRow){d.selectedRow=b.dataset.value;renderQuestion(q,b.id);}
    if(b.dataset.matchTarget&&d.selectedRow){d.answer[d.selectedRow]=b.dataset.value;renderQuestion(q,b.id);}
    if(b.dataset.orderAdd&&!d.answer.includes(b.dataset.value)){d.answer.push(b.dataset.value);renderQuestion(q,`${q.id}-remove-${b.dataset.value}`);}
    if(b.dataset.orderRemove){d.answer=d.answer.filter(v=>v!==b.dataset.value);renderQuestion(q,`${q.id}-add-${b.dataset.value}`);}
    if(b.dataset.check&&isComplete(q,d.answer)){const correct=isCorrect(q,d.answer);const result=recordAttempt(active(),q.id,correct);commit(result.session);d.status=correct?'correct':'wrong';renderQuestion(q);updateLessonFooter();}
  }
  if(b.id==='lesson-finish')showResults();
});
// 本頁的區段連結只捲動，不觸發課程換頁。
document.addEventListener('click',e=>{const a=e.target.closest('a');if(!a)return;const hash=a.getAttribute('href');if(['#concept','#explore','#practice','#start-form','#main'].includes(hash)){e.preventDefault();document.querySelector(hash)?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'});}});
window.addEventListener('hashchange',render);
render();

